# Generated by Django 2.1.2 on 2018-10-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0002_auto_20181018_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='applicants',
            new_name='students',
        ),
    ]
